"""empty message

Revision ID: 62f7370a11a4
Revises: 4563894e92cd
Create Date: 2021-01-26 14:55:39.885151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62f7370a11a4'
down_revision = '4563894e92cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mahasiswa_ibfk_1', 'mahasiswa', type_='foreignkey')
    op.drop_column('mahasiswa', 'fakultas')
    op.add_column('prodi', sa.Column('id_fakultas', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prodi', 'fakultas', ['id_fakultas'], ['id_fakultas'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prodi', type_='foreignkey')
    op.drop_column('prodi', 'id_fakultas')
    op.add_column('mahasiswa', sa.Column('fakultas', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('mahasiswa_ibfk_1', 'mahasiswa', 'fakultas', ['fakultas'], ['id_fakultas'], ondelete='CASCADE')
    # ### end Alembic commands ###
